version: '3.8'

services:
  server:
    build: ./server
    env_file: ./server/.env
    ports:
      - "3005:3005"

  client:
    build: ./client
    ports:
      - "3000:80"

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
